
[package]
name = "os"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
test-kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}

[dependencies]

[workspace]
members = ["kernel", "simple_kernel"]