#[cfg(feature = "string_opcodes")]
pub mod string;
#[cfg(feature = "atomic_opcodes")]
pub mod atomic;
#[cfg(feature = "crypto_opcodes")]
pub mod crypto;
#[cfg(feature = "memory_opcodes")]
pub mod memory;
#[cfg(feature = "io_port_opcodes")]
pub mod io_port;
#[cfg(feature = "threednow_opcodes")]
pub mod threednow;
#[cfg(feature = "system_opcodes")]
pub mod system;
#[cfg(feature = "virtualization_opcodes")]
pub mod virtualization;
#[cfg(feature = "legacy_opcodes")]
pub mod legacy;
#[cfg(feature = "control_flow_opcodes")]
pub mod control_flow;
#[cfg(feature = "nop_opcodes")]
pub mod nop;
#[cfg(feature = "simd_opcodes")]
pub mod simd;
#[cfg(feature = "core_opcodes")]
pub mod core;
#[cfg(feature = "data_movement_opcodes")]
pub mod data_movement;
#[cfg(feature = "integer_opcodes")]
pub mod integer;
#[cfg(feature = "fpu_opcodes")]
pub mod fpu;
