[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-nodefaultlibs",
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
]
