#[cfg(feature = "x16_real_mode")]
pub mod x16_real_mode;
#[cfg(feature = "x16_protected_mode")]
pub mod x16_protected_mode;
#[cfg(feature = "x32_mode")]
pub mod x32_mode;
#[cfg(feature = "x64_mode")]
pub mod x64_mode;
#[cfg(feature = "virtual8086_mode")]
pub mod virtual8086_mode;
